SUBJECTS_DATA = [
    {"code": "MAT101", "name": "Cálculo I", "emoji": "📐", "area": "Matemáticas", "students_count": 24, "sessions_count": 5},
    {"code": "INF119", "name": "Estructuras Discretas", "emoji": "🔢", "area": "Informática", "students_count": 18, "sessions_count": 3},
    {"code": "INF110", "name": "Introducción a la Informática", "emoji": "💻", "area": "Informática", "students_count": 30, "sessions_count": 6},
    {"code": "FIS100", "name": "Física I", "emoji": "⚡", "area": "Física", "students_count": 16, "sessions_count": 4},
    {"code": "LIN100", "name": "Inglés Técnico I", "emoji": "🇬🇧", "area": "Idiomas", "students_count": 14, "sessions_count": 2},
    {"code": "MAT102", "name": "Cálculo II", "emoji": "📐", "area": "Matemáticas", "students_count": 20, "sessions_count": 4},
    {"code": "MAT103", "name": "Álgebra Lineal", "emoji": "📊", "area": "Matemáticas", "students_count": 22, "sessions_count": 5},
    {"code": "INF120", "name": "Programación I", "emoji": "💻", "area": "Programación", "students_count": 35, "sessions_count": 8},
    {"code": "FIS102", "name": "Física II", "emoji": "🧲", "area": "Física", "students_count": 15, "sessions_count": 3},
    {"code": "LIN101", "name": "Inglés Técnico II", "emoji": "📖", "area": "Idiomas", "students_count": 12, "sessions_count": 2},
    {"code": "MAT207", "name": "Ecuaciones Diferenciales", "emoji": "📈", "area": "Matemáticas", "students_count": 17, "sessions_count": 4},
    {"code": "INF210", "name": "Programación II", "emoji": "☕", "area": "Programación", "students_count": 28, "sessions_count": 6},
    {"code": "INF211", "name": "Arquitectura de Computadoras", "emoji": "🖥️", "area": "Hardware", "students_count": 19, "sessions_count": 3},
    {"code": "FIS200", "name": "Física III", "emoji": "🔬", "area": "Física", "students_count": 11, "sessions_count": 2},
    {"code": "ADM100", "name": "Administración", "emoji": "📋", "area": "Administración", "students_count": 15, "sessions_count": 3},
    {"code": "MAT202", "name": "Probabilidades y Estadísticas I", "emoji": "🎲", "area": "Matemáticas", "students_count": 21, "sessions_count": 5},
    {"code": "MAT205", "name": "Métodos Numéricos", "emoji": "⚙️", "area": "Matemáticas", "students_count": 16, "sessions_count": 3},
    {"code": "INF220", "name": "Estructura de Datos I", "emoji": "🌳", "area": "Programación", "students_count": 29, "sessions_count": 7},
    {"code": "INF221", "name": "Programación Ensamblador", "emoji": "🧩", "area": "Programación", "students_count": 14, "sessions_count": 3},
    {"code": "ADM200", "name": "Contabilidad", "emoji": "💳", "area": "Administración", "students_count": 13, "sessions_count": 2},
    {"code": "MAT302", "name": "Probabilidades y Estadísticas II", "emoji": "📉", "area": "Matemáticas", "students_count": 16, "sessions_count": 3},
    {"code": "INF318", "name": "Programación Lógica y Funcional", "emoji": "λ", "area": "Programación", "students_count": 18, "sessions_count": 4},
    {"code": "INF310", "name": "Estructura de Datos II", "emoji": "📦", "area": "Programación", "students_count": 22, "sessions_count": 5},
    {"code": "INF312", "name": "Base de Datos I", "emoji": "🗄️", "area": "Base de Datos", "students_count": 31, "sessions_count": 7},
    {"code": "INF319", "name": "Lenguajes Formales", "emoji": "📜", "area": "Informática", "students_count": 17, "sessions_count": 3},
    {"code": "MAT329", "name": "Investigación Operativa I", "emoji": "🎯", "area": "Matemáticas", "students_count": 19, "sessions_count": 4},
    {"code": "INF342", "name": "Sistemas de Información I", "emoji": "🏢", "area": "Sistemas", "students_count": 25, "sessions_count": 5},
    {"code": "INF323", "name": "Sistemas Operativos I", "emoji": "🐧", "area": "Sistemas", "students_count": 26, "sessions_count": 6},
    {"code": "INF322", "name": "Base de Datos II", "emoji": "💾", "area": "Base de Datos", "students_count": 23, "sessions_count": 5},
    {"code": "INF329", "name": "Compiladores", "emoji": "⚙️", "area": "Informática", "students_count": 15, "sessions_count": 3},
    {"code": "MAT419", "name": "Investigación Operativa II", "emoji": "♟️", "area": "Matemáticas", "students_count": 14, "sessions_count": 3},
    {"code": "INF418", "name": "Inteligencia Artificial", "emoji": "🤖", "area": "IA", "students_count": 34, "sessions_count": 8},
    {"code": "INF413", "name": "Sistemas Operativos II", "emoji": "🛡️", "area": "Sistemas", "students_count": 18, "sessions_count": 4},
    {"code": "INF433", "name": "Redes I", "emoji": "🌐", "area": "Redes", "students_count": 27, "sessions_count": 6},
    {"code": "INF412", "name": "Sistemas de Información II", "emoji": "📊", "area": "Sistemas", "students_count": 22, "sessions_count": 4},
    {"code": "ECO449", "name": "Preparación y Evaluación de Proyectos", "emoji": "📑", "area": "Economía", "students_count": 16, "sessions_count": 3},
    {"code": "INF428", "name": "Sistemas Expertos", "emoji": "🧠", "area": "IA", "students_count": 19, "sessions_count": 4},
    {"code": "INF442", "name": "Sistemas de Información Geográfica", "emoji": "🗺️", "area": "Sistemas", "students_count": 13, "sessions_count": 2},
    {"code": "INF423", "name": "Redes II", "emoji": "📡", "area": "Redes", "students_count": 21, "sessions_count": 5},
    {"code": "INF422", "name": "Ingeniería de Software I", "emoji": "🏗️", "area": "Software", "students_count": 28, "sessions_count": 6},
    {"code": "INF511", "name": "Taller de Grado I", "emoji": "🎓", "area": "Graduación", "students_count": 20, "sessions_count": 4},
    {"code": "INF512", "name": "Ingeniería de Software II", "emoji": "🚀", "area": "Software", "students_count": 25, "sessions_count": 5},
    {"code": "INF513", "name": "Tecnología Web", "emoji": "🌐", "area": "Web", "students_count": 33, "sessions_count": 7},
    {"code": "INF552", "name": "Arquitectura del Software", "emoji": "🏛️", "area": "Software", "students_count": 22, "sessions_count": 5},
    {"code": "GRL001", "name": "Modalidad de Titulación Licenciatura", "emoji": "📜", "area": "Graduación", "students_count": 15, "sessions_count": 3},
    {"code": "ELC101", "name": "Modelación y Simulación de Sistemas", "emoji": "🧪", "area": "Electivas", "students_count": 12, "sessions_count": 2},
    {"code": "ELC102", "name": "Programación Gráfica", "emoji": "🎨", "area": "Electivas", "students_count": 14, "sessions_count": 3},
    {"code": "ELC103", "name": "Tópicos Avanzados de Programación", "emoji": "⚡", "area": "Electivas", "students_count": 16, "sessions_count": 3},
    {"code": "ELC104", "name": "Programación de aplicaciones de Tiempo Real", "emoji": "⏱️", "area": "Electivas", "students_count": 11, "sessions_count": 2},
    {"code": "ELC105", "name": "Sistemas Distribuidos", "emoji": "☁️", "area": "Electivas", "students_count": 18, "sessions_count": 4},
    {"code": "ELC106", "name": "Interacción Hombre-Computador", "emoji": "🤝", "area": "IHC", "students_count": 32, "sessions_count": 8},
    {"code": "ELC107", "name": "Criptografía y Seguridad", "emoji": "🔒", "area": "Seguridad", "students_count": 23, "sessions_count": 5},
    {"code": "ELC108", "name": "Control y Automatización", "emoji": "🤖", "area": "Automatización", "students_count": 13, "sessions_count": 3},
]
